config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :expenses
  resources :categories do
    resources :expenses, only: [:new, :create]
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :icon, presence: true

  belongs_to :user
  has_and_belongs_to_many :expenses, foreign_key: :category_id, dependent: :destroy

  def total_amount
    expenses.map(&:amount).reduce(:+) || 0
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.where(user: current_user).order(created_at: :desc)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @expenses = Expense.where(user_id: current_user.id, category_id: @category.id).order(created_at: :desc)
  end

  # GET /categories/new
  def new
    @category = current_user.categories.build
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.build(category_params)

    respond_to do |format|
      if @category.save
        format.html do
          redirect_to categories_url, notice: "Category #{category_params[:name]} was successfully created."
        end
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    Expense.where(user_id: current_user.id, category_id: @category.id).destroy_all
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <%= link_to category, id: dom_id(category) do %>
    <li class="p-4 hover:bg-neutral-200 transition-ease-in-out duration-500 flex justify-between p- mb-5 border border-neutral-300 shadow bg-white">
      
      <div class=" flex flex-col justify-between flex-1 gap-3">
        <h3 class="text-xl"><%= category.name %></h3>
        <img src="<%= category.icon %>" alt="<%= category.name %>'s icon" class="w-[70px] h-[70px] object-cover">
      </div>
      <div class="">
        <p class="font-bold">$<%= category.total_amount.round(2) %></p>
      </div>
    </li>
  <% end %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "w-full bg-white flex flex-col") do |form| %>
  <% if category.errors.any? %>
    <div class="m-auto text-red-500 flex flex-col" id="error_explanation">
      <ul class="m-auto mt-5 m-auto py-2 px-3 bg-red-50 text-red-500 font-medium rounded-lg inline-block">
        <% category.errors.full_messages.each do |msg| %>
          <li>🎯<%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
      <%= form.text_field :name, placeholder: "Name", class: 'mt-4 placeholder-[#babfc6] w-full border-t-[#babfc5] border-transparent w-full', required: true %>
  </div>
  <hr class="m-auto w-[95%]">
  <div class="p-4 w-full flex flex-col">
    <%= form.label :icon, class: "text-[#babfc6] mb-4" %>
    <%= form.select :icon, options_for_select([
      ["🚗", "https://img.icons8.com/2266EE/color/sedan"],
      ["🏠", "https://img.icons8.com/2266EE/color/home"],
      ["🥗", "https://img.icons8.com/2266EE/color/food-receiver"],
      ["🏥", "https://img.icons8.com/2266EE/color/hospital"],
      ["💹", "https://img.icons8.com/2266EE/color/bank"],
      ["🏈", "https://img.icons8.com/2266EE/color/sport"],
      ["🐕‍🦺", "https://img.icons8.com/2266EE/color/dog"],
      ["👜", "https://img.icons8.com/2266EE/color/plastic-bag"],
      ["👤", "https://img.icons8.com/2266EE/color/user"],
      ["🐈‍⬛", "https://img.icons8.com/2266EE/color/cat"],
    ]), class: '', id: 'icon-select' %>
  </div>

  <div class="">
    <%= form.submit "Create", id: "hidden-submit_3", class: "hidden" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<section class="w-full h-screen flex flex-col items-center">
  <div class="mb-4 flex flex-col w-full max-w-[568px]">
    <div class="sticky flex head-gradient max-w-[568px] top-0 w-full w-full min-w-[350px] items-center px-4 pt-8 pb-2">
      <%= link_to(categories_path, class: "") do %>
        <span class="material-symbols-outlined text-white hover:text-neutral-300">arrow_back_ios</span>
      <% end %>
      <h2 class="text-white m-auto">EDIT CATEGORY</h2>
      <button class="text-white text-[14px] hover:text-neutral-200" onclick="document.getElementById('hidden-submit_3').click()">Save</button>
    </div>

    <div class="mx-auto w-full">
      <%= render "form", category: @category %>
      <div class="inline-block mt-2 flex justify-end">
        <%= button_to category_path(@category), method: :delete, class: "text-neutral-500 hover:text-neutral-700 mt-2" do %>
          <span class="material-symbols-outlined justify-self-end">delete</span>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/categories/index.html.erb
<section class="w-full h-full flex flex-col items-center special-margin">
  <div class="mb-4 flex flex-col w-full max-w-[568px]">
    <div class="fixed flex head-gradient max-w-[568px] top-0 w-full w-full min-w-[350px] items-center px-4 pt-8 pb-2">
      <% if user_signed_in? %>
        <%= button_to destroy_user_session_path, method: :delete, class: "logout-button text-black hover:text-red-500" do %>
          <span class="material-symbols-outlined text-white hover:text-neutral-300">logout</span>
        <% end %>
      <% end %>
      <h2 class="text-white m-auto pb-2">CATEGORIES</h2>
    </div>

    <div class="mb-[10px] fixed total-spent w-full max-w-[568px] flex justify-between p-4 w-full bg-white border text-neutral-600 border-neutral-300">
      <h2 class="">Total:</h2>
       <b>$<%= current_user.total_spent %></b>
    </div>
    
    <div class="margin-t flex w-full flex-col">
      <% if alert.present? %>
        <p class="m-auto py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
      <% end %>

      <% if notice.present? %>
        <p class="m-auto py-2 px-3 bg-green-50 mb-4 text-green-500 font-medium rounded-lg inline-block transition-opacity duration-500" id="notice"><%= notice %></p>
        <%= hide_notice_after(4) %>
      <% end %>

      <div id="categories" class=" w-full transition-ease-in duration-500 mb-[90px]">
        <%= render @categories %>
      </div>

      <div class="transition-ease-in w-full fixed max-w-[568px] bottom-0 flex items-center bg-[#5fb523] hover:bg-[#478e16] p-4 transition-ease-in-out duration-500">
        <%= link_to 'NEW CATEGORY', new_category_path, class: " rounded-sm border-2 border-neutral-100 flex justify-center text-white w-full min-w-[350px] items-center p-4", id: "new-category'" %>
      </div>
    </div>
  </div>
</section>

app/views/categories/new.html.erb
<section class="w-full h-screen flex flex-col items-center">
  <div class="mb-4 flex flex-col w-full max-w-[568px]">
    <div class="sticky flex head-gradient max-w-[568px] top-0 w-full w-full min-w-[350px] items-center px-4 pt-8 pb-2">
      <%= link_to('javascript:history.back()', class: "") do %>
        <span class="material-symbols-outlined text-white">arrow_back_ios</span>
      <% end %>
      <h2 class="text-white m-auto">NEW CATEGORY</h2>
      <button id="create-category" class="text-white text-[14px]" onclick="document.getElementById('hidden-submit_3').click()">Create</button>
    </div>

    <div class="mx-auto w-full">

      <%= render "form", category: @category %>

    </div>
  </div>
</section>

app/views/categories/show.html.erb
<section class="w-full h-full flex flex-col items-center">
  <div class="mb-4 flex flex-col w-full max-w-[568px]">
    <div class="sticky flex head-gradient max-w-[568px] top-0 w-full w-full min-w-[350px] items-center px-4 pt-8 pb-2">
      <%= link_to(categories_path, class: "") do %>
        <span class="material-symbols-outlined text-white hover:text-neutral-300">arrow_back_ios</span>
      <% end %>
      <h2 class="text-white m-auto"><%= @category.name.upcase %></h2>
      <%= link_to 'Edit', edit_category_path(@category), class: "hover:text-neutral-300 text-white text-[16px]" %>
    </div>
    <div class="items-center total-spent w-full max-w-[568px] m-auto p-4 w-full bg-white border text-neutral-600 border-neutral-300 flex">
      <img src="<%= @category.icon %>" alt="<%= @category.name %>'s icon" class=" w-[40px] h-[40px] object-cover">
      <h2 class="ml-4">Total Spent:</h2>
      <b class="ml-auto">$<%= @category.expenses.map(&:amount).reduce(:+) || 0 %></b>
    </div>
    <% if notice.present? %>
      <p class="m-auto py-2 px-3 bg-green-50 mt-5 text-green-500 font-medium rounded-lg inline-block transition-opacity duration-500" id="notice"><%= notice %></p>
      <%= hide_notice_after(4) %>
    <% end %>
    <% if alert.present? %>
      <p class="m-auto py-2 px-3 bg-green-50 mt-5 text-green-500 font-medium rounded-lg inline-block transition-opacity duration-500" id="alert"><%= alert %></p>
      <%= hide_alert_after(4) %>
    <% end %>
    <div class="mt-5 mx-auto w-full flex flex-col items-center">
      <div class="mx-auto w-full">
        <div class="total-spent w-full max-w-[568px]">
          <%= render @category.expenses %>
        </div>

        <div class="m-auto fixed transition-ease-in w-full max-w-[568px] bottom-0 flex items-center bg-[#5fb523] hover:bg-[#478e16] p-4 transition-ease-in-out duration-500">
          <%= link_to 'NEW EXPENSE', new_category_expense_path(@category, category_id: @category.id), class: "m-auto rounded-sm border-2 border-neutral-100 flex justify-center text-white w-full min-w-[350px] items-center p-4" %>
        </div>
      </div>
    </div>
  </div>
</section>