config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :expenses
  resources :categories do
    resources :expenses, only: [:new, :create]
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true

  has_many :expenses, foreign_key: :user_id, dependent: :destroy
  has_many :categories, foreign_key: :user_id, dependent: :destroy

  def total_spent
    categories.sum { |category| category.expenses.sum(&:amount) } || 0
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[show edit update destroy]

  # GET /expenses or /expenses.json
  def index
    @category = Category.find(params[:category_id])
    @expenses = @category.expenses.order(id: :desc)
  end

  # GET /expenses/1 or /expenses/1.json
  def show; end

  # GET /expenses/new
  def new
    @category = Category.find(params[:category_id])
    @expense = current_user.expenses.build
    @categories = Category.where(user: current_user).order(created_at: :desc)
  end

  # GET /expenses/1/edit
  def edit; end

  # POST /expenses or /expenses.json
  def create
    @category = Category.find(params[:category_id])
    @expense = current_user.expenses.build(expense_params)
    @expense.user_id = current_user.id
    @category.expenses << @expense
    category_ids = params[:category_ids]

    categories = Category.where(id: category_ids)
    categories.each do |category|
      category.expenses << @expense
    end

    respond_to do |format|
      if @expense.save
        format.html { redirect_to category_url(@category), notice: 'expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: 'expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to category_url(@expense.category_id), notice: 'expense was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:user_id, :name, :amount, :category_id)
  end

  def categories
    main_category = Category.find(params[:category_id])

    extra_categories = params[:categories] ? Category.where(id: params[:categories][:category_ids]).to_a : []
    categories = []

    categories << main_category << extra_categories
    categories.flatten
  end
end

app/views/expenses/_expense.html.erb
<li class="mx-5 transition-ease-in-out duration-500 flex justify-between p-2 mb-4 border border-neutral-300 shadow bg-white">
  <div id="<%= dom_id expense %>" class="flex w-full justify-between">
    <div class="flex flex-col justify-between">
      <p class="mb-4">
        <%= expense.name %>
      </p>
      <%= button_to expense_path(expense), method: :delete, class: "text-neutral-500 hover:text-neutral-700 mt-2" do %>
        <span class="material-symbols-outlined">delete</span>
      <% end %>
    </div>
    <div class="flex flex-col justify-between">
      <p class="flex justify-end font-bold">
        <%= number_to_currency(expense.amount, precision: 1) %>
      </p>
      <p class="mt-5 text-[12px]">
        <%= expense.created_at.to_date.strftime('%d-%m-%Y') %>
      </p>
    </div>

    <% if action_name != "show" %>
      <%= link_to "Show this expense", expense, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to 'Edit this expense', edit_expense_path(expense), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
      <hr class="mt-6">
    <% end %>
  </div>
</li>

app/views/expenses/_form.html.erb
<%= form_with(model: [@category, @expense], class: "w-full bg-white flex flex-col") do |form| %>
  <% if expense.errors.any? %>
    <div id="error_explanation" class="m-auto text-red-500 flex flex-col" id="error_explanation">
      <ul class="m-auto mt-5 m-auto py-2 px-3 bg-red-50 text-red-500 font-medium rounded-lg inline-block">
        <% expense.errors.each do |error| %>
          <li>🎯<%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :category_id, value: @category.id %>
  <input type="hidden" name="categoryIds" id="categoryIds" value="" />

  <div class="w-full">
    <%= form.text_field :name, placeholder: "Name", class: 'mt-4 placeholder-[#babfc6] w-full border-t-[#babfc5] border-transparent w-full', required: true %>
  </div>
  <hr class="m-auto w-[95%]">
  <div class="">
    <%= form.text_field :amount, placeholder: "Amount", class: 'placeholder-[#babfc6] w-full border-b-[#babfc5] border-transparent w-full', required: true %>
  </div>
  <h2 class="mt-2 p-2 w-full bg-white shadow">Select related categories 👇🏽</h2>
  <div class="grid grid-cols-2">
    <% Category.where.not(id: @category.id).each do |category| %>
      <div class="flex items-center p-4">
        <%= check_box_tag 'category_ids[]', category.id %>
        <%= image_tag category.icon, alt: category.name, class: "w-6 h-6 inline-block ml-2" %>
        <%= label_tag "category_#{category.id}", category.name, class: "ml-4" %>
      </div>
    <% end %>
  </div>
  <div class="">
    <%= form.submit "Create", id: "hidden-submit_4", class: "hidden" %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing expense</h1>

  <%= render "form", expense: @expense %>

  <%= link_to "Show this expense", @expense, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to expenses", expenses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/expenses/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Expenses</h1>
    <%= link_to 'New expense', new_expense_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="expenses" class="min-w-full">
    <%= render @expenses %>
  </div>
</div>

app/views/expenses/new.html.erb
<section class="w-full h-screen flex flex-col items-center">
  <div class="mb-4 flex flex-col w-full max-w-[568px]">
    <div class="sticky flex head-gradient max-w-[568px] top-0 w-full w-full min-w-[350px] items-center px-4 pt-8 pb-2">
      <%= link_to('javascript:history.back()', class: "") do %>
        <span class="material-symbols-outlined text-white">arrow_back_ios</span>
      <% end %>
      <h2 class="text-white m-auto">NEW EXPENSE</h2>
      <button class="text-white text-[14px]" onclick="document.getElementById('hidden-submit_4').click()">Create</button>
    </div>

    <div class="mx-auto w-full shadow">
      <%= render "form", expense: @expense %>
    </div>
  </div>
</section>

app/views/expenses/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @expense %>

    <%= link_to 'Edit this expense', edit_expense_path(@expense), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this expense', expense_path(@expense), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to expenses', expenses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>